function [err, pso] = pso_lost_function(x, y, p)
    x = reshape(x, [], 1);
    y = reshape(y, [], 1);
    pso = struct('x', zeros(30, 1), ...
                 'yref', zeros(30, 1), ...
                 'yprd', zeros(30, 1), ...
                 'beta', p, ...
                 'fitness', 0, ...
                 'fun', @(beta, x) (beta(1) * (1 - exp(-1 * (x ./ beta(2)) .^ beta(3)))));

    [pso.x, pso.yref] = sort_by_dmax('x', x, 'y', y, 'dmax', p(4));
    pso.yprd = pso.fun(pso.beta, pso.x); % p(1) * (1 - exp(-1 * (dBar .^ p(3)) ./ (p(2) ^ p(3))));
    err = sqrt(mean((pso.yprd - pso.yref) .^ 2));
    pso.fitness = err;
end